<?php

$ignore_list = [
    "Curaçao",
        "Cura&ccedil;ao",
    "Réunion",
        "R&eacute;union",
    "Vatican City",
    "Guadeloupe",
    "French Polynesia",
    "Martinique",
    "French Guiana",
    "Mayotte",
    "Timor-Leste",
    "Aruba",
    "South Sudan",
    "Channel Islands",
    "Isle of Man",
    "Gibraltar",
    "Sint Maarten",
    "Saint Martin",
    "Liechtenstein",
    "Bermuda",
    "Turks and Caicos",
    "British Virgin Islands",
    "Caribbean Netherlands",
    "St. Barth",
    "Faeroe Islands",
    "Cayman Islands",
    "Wallis and Futuna",
    "Greenland",
    "Anguilla",
    "New Caledonia",
    "Falkland Islands",
    "Macao",
    "Saint Pierre Miquelon",
    "Vatican City",
    "Montserrat",
    "Western Sahara",
    "Saint Helena",
    "China"
];