<?php

$ignore_list = [
    "Curaçao",
        "Cura&ccedil;ao",
    "Réunion",
        "R&eacute;union",
    "Russia",
    "Turkey",
    "Iran",
    "Colombia",
    "Ukraine",
    "DPRK",
    "Iraq",
    "Bangladesh",
    "Jordan",
    "Georgia",
    "Pakistan",
    "Kazakhstan",
    "Morocco",
    "Cuba",
    "Lebanon",
    "Tunisia",
    "Belarus",
    "Nepal",
    "UAE",
    "Ecuador",
    "Guatemala",
    "Panama",
    "Azerbaijan",
    "Saudi Arabia",
    "Sri Lanka",
    "Paraguay",
    "Kuwait",
    "Myanmar",
    "Bahrain",
    "Dominican Republic",
    "Palestine",
    "Venezuela",
    "Moldova",
    "Egypt",
    "Libya",
    "Cyprus",
    "Ethiopia",
    "Mongolia",
    "Honduras",
    "Armenia",
    "Oman",
    "Qatar",
    "Kenya",
    "Zambia",
    "North Macedonia",
    "Botswana",
    "Albania",
    "Algeria",
    "Nigeria",
    "Zimbabwe",
    "Uzbekistan",
    "Montenegro",
    "Mozambique",
    "China",
    "Laos",
    "Kyrgyzstan",
    "Afghanistan",
    "Maldives",
    "Martinique",
    "Namibia",
    "Uganda",
    "El Salvador",
    "Ghana",
    "Trinidad and Tobago",
    "Brunei",
    "Guadeloupe",
    "Cambodia",
    "Rwanda",
    "Cameroon",
    "Angola",
    "Malta",
    "DRC",
    "Senegal",
    "Malawi",
    "French Guiana",
    "Ivory Coast",
    "Suriname",
    "Barbados",
    "Channel Islands",
    "French Polynesia",
    "Eswatini",
    "Fiji",
    "Guyana",
    "Madagascar",
    "Sudan",
    "New Caledonia",
    "Bhutan",
    "Mauritania",
    "Belize",
    "Cabo Verde",
    "Syria",
    "Gabon",
    "Papua New Guinea",
    "Seychelles",
    "Andorra",
    "Burundi",
    "Mauritius",
    "Mayotte",
    "Togo",
    "Aruba",
    "Guinea",
    "Tanzania",
    "Faeroe Islands",
    "Bahamas",
    "Lesotho",
    "Mali",
    "Haiti",
    "Isle of Man",
    "Benin",
    "Somalia",
    "Saint Lucia",
    "Cayman Islands",
    "Congo",
    "Timor-Leste",
    "Burkina Faso",
    "Nicaragua",
    "Gibraltar",
    "Solomon Islands",
    "Grenada",
    "South Sudan",
    "Tajikistan",
    "San Marino",
    "Equatorial Guinea",
    "Djibouti",
    "Bermuda",
    "CAR",
    "Dominica",
    "Samoa",
    "Monaco",
    "Gambia",
    "Greenland",
    "Yemen",
    "Tonga",
    "Saint Martin",
    "Sint Maarten",
    "Caribbean Netherlands",
    "Eritrea",
    "Niger",
    "Vanuatu",
    "Guinea-Bissau",
    "Antigua and Barbuda",
    "Comoros",
    "Sierra Leone",
    "Liberia",
    "Chad",
    "St. Vincent Grenadines",
    "British Virgin Islands",
    "Turks and Caicos",
    "Sao Tome and Principe",
    "Saint Kitts and Nevis",
    "Cook Islands",
    "Palau",
    "St. Barth",
    "Anguilla",
    "Kiribati",
    "Saint Pierre Miquelon",
    "Falkland Islands",
    "Montserrat",
    "Diamond Princess",
    "Wallis and Futuna",
    "Macao",
    "Micronesia",
    "Vatican City",
    "Marshall Islands",
    "Western Sahara",
    "MS Zaandam",
    "Niue",
    "Nauru",
    "Tuvalu",
    "Saint Helena"
];